# SPDX-License-Identifier: GPL-3.0-or-later
<#
Pushes this repository to GitHub through the REST API - no local git installation
needed.  It creates one commit (Git Data API: blobs -> tree -> commit -> ref), so
files that already exist in the repo but are not part of the upload set are left
alone (the new tree is based on the current branch head).

Usage
-----
    # preview only, no token required
    pwsh tools\upload-github.ps1 -DryRun

    # upload
    $env:GITHUB_TOKEN = 'github_pat_...'
    pwsh tools\upload-github.ps1

    # upload and publish the built jars as a release
    pwsh tools\upload-github.ps1 -ReleaseTag v1.0.5 -ReleaseName 'WATERMeDIA: Android Bridge 1.0.5' -Version 1.0.5

Token: a fine-grained personal access token with "Contents: Read and write" on this
repository is enough.  Revoke it right after the upload.

What is uploaded (mirrors .gitignore): .gitignore, LICENSE, README.md,
docs/TECHNICAL.md, src/main/java/**, the text resources under src/main/resources
(the generated native payload is regenerated by tools/pack-payload.ps1) and
tools/**.  docs/DEVELOPMENT-LOG.md, vendor/, build/, dist/ and logs/ stay local.
#>
param(
  [string]$Token = $env:GITHUB_TOKEN,
  [string]$Owner = 'mingyu-games-wmjbfs',
  [string]$Repo = 'WATERMeDIA-Android-Bridge',
  [string]$Branch = '',
  [string]$Message = '1.0.5 - fix the blank/white video screen (GLES pixel type, vmem vout, MediaCodec) and add video diagnostics',
  [string]$ReleaseTag = '',
  [string]$ReleaseName = 'WATERMeDIA: Android Bridge 1.0.5 - 1.21.1 Fabric / 1.21.1 NeoForge / 1.20.1 Fabric / 1.20.1 Forge',
  [string]$ReleaseBody = '',
  [string]$Version = '',
  [string[]]$Topics = @(),
  # Repository paths that this upload set no longer contains (files that were moved or
  # deleted locally).  Git trees are additive, so a moved file would otherwise survive at
  # its old path forever.  A null "sha" in the tree removes the path.
  [string[]]$RemovePaths = @(),
  [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent

function Get-UploadFiles {
  # built with += instead of List.AddRange: Windows PowerShell 5.1 does not convert
  # the Object[] that ForEach-Object produces into IEnumerable[string].
  $files = @()
  foreach ($relative in @('.gitignore', 'LICENSE', 'README.md', 'README.en.md', 'docs/TECHNICAL.md', 'docs/RELEASE-NOTES.md', 'docs/RELEASE-NOTES.en.md')) {
    $full = Join-Path $root $relative
    if (Test-Path $full) { $files += $full } else { Write-Host "[warn] missing $relative" }
  }
  $files += @(Get-ChildItem (Join-Path $root 'src\main\java') -Recurse -File |
      ForEach-Object { $_.FullName })
  # the per-loader entry points, metadata and pack.mcmeta live outside src/main
  $files += @(Get-ChildItem (Join-Path $root 'src\loader') -Recurse -File |
      ForEach-Object { $_.FullName })
  $files += @(Get-ChildItem (Join-Path $root 'src\main\resources') -Recurse -File |
      Where-Object { $_.FullName -notmatch 'watermedia_android[\\/](natives|jna)' } |
      ForEach-Object { $_.FullName })
  $files += @(Get-ChildItem (Join-Path $root 'tools') -Recurse -File |
      ForEach-Object { $_.FullName })
  return @($files | Sort-Object -Unique)
}

function Get-RelativePath([string]$full) {
  return $full.Substring($root.Length + 1).Replace('\', '/')
}

$upload = Get-UploadFiles
$totalBytes = ($upload | ForEach-Object { (Get-Item $_).Length } | Measure-Object -Sum).Sum
Write-Host ("upload set: {0} files, {1:N1} KB" -f $upload.Count, ($totalBytes / 1KB))

if ($DryRun) {
  Write-Host ''
  foreach ($file in $upload) {
    Write-Host ("{0,9:N0} B  {1}" -f (Get-Item $file).Length, (Get-RelativePath $file))
  }
  Write-Host ''
  Write-Host 'dry run only - nothing was sent to GitHub'
  return
}

if (-not $Token) {
  throw 'no token: pass -Token or set the GITHUB_TOKEN environment variable'
}

$tmp = Join-Path $env:TEMP ('gh-upload-' + [guid]::NewGuid().ToString('N'))
New-Item -ItemType Directory -Force -Path $tmp | Out-Null
$utf8 = New-Object System.Text.UTF8Encoding($false)

function Invoke-GitHubApi {
  param([string]$Method, [string]$Path, $Body)
  $bodyFile = Join-Path $tmp 'body.json'
  $respFile = Join-Path $tmp 'response.json'
  if (Test-Path $respFile) { Remove-Item $respFile -Force }
  $arguments = @(
    '-sS', '--ssl-no-revoke', '-X', $Method,
    '-H', "Authorization: Bearer $Token",
    '-H', 'Accept: application/vnd.github+json',
    '-H', 'X-GitHub-Api-Version: 2022-11-28',
    '-H', 'User-Agent: watermedia-android-bridge-uploader',
    '-w', '%{http_code}', '-o', $respFile
  )
  if ($null -ne $Body) {
    [System.IO.File]::WriteAllText($bodyFile, ($Body | ConvertTo-Json -Depth 8 -Compress), $utf8)
    $arguments += @('--data-binary', "@$bodyFile")
  }
  $arguments += "https://api.github.com$Path"
  $code = (& curl.exe @arguments) -join ''
  $text = if (Test-Path $respFile) { [System.IO.File]::ReadAllText($respFile, $utf8) } else { '' }
  if ($code -notmatch '^2\d\d$') {
    throw "GitHub API $Method $Path -> HTTP $code`n$text"
  }
  if ([string]::IsNullOrWhiteSpace($text)) { return $null }
  return ($text | ConvertFrom-Json)
}

$repoInfo = Invoke-GitHubApi -Method GET -Path "/repos/$Owner/$Repo"
if (-not $Branch) { $Branch = $repoInfo.default_branch }
if (-not $Branch) { $Branch = 'main' }
Write-Host ("repository: {0} (private={1}), branch '{2}'" -f $repoInfo.full_name, $repoInfo.private, $Branch)

$headCommit = $null
$baseTree = $null
try {
  $reference = Invoke-GitHubApi -Method GET -Path "/repos/$Owner/$Repo/git/ref/heads/$Branch"
  $headCommit = $reference.object.sha
  $head = Invoke-GitHubApi -Method GET -Path "/repos/$Owner/$Repo/git/commits/$headCommit"
  $baseTree = $head.tree.sha
  Write-Host "branch head: $headCommit"
} catch {
  Write-Host "[info] branch '$Branch' has no commit yet - this will be the first commit"
}

$entries = New-Object System.Collections.Generic.List[object]
foreach ($file in $upload) {
  $relative = Get-RelativePath $file
  $encoded = [Convert]::ToBase64String([System.IO.File]::ReadAllBytes($file))
  $blob = Invoke-GitHubApi -Method POST -Path "/repos/$Owner/$Repo/git/blobs" -Body @{
    content = $encoded
    encoding = 'base64'
  }
  $entries.Add(@{ path = $relative; mode = '100644'; type = 'blob'; sha = $blob.sha })
  Write-Host "  uploaded $relative"
}

foreach ($removed in $RemovePaths) {
  $relative = $removed.Replace('\', '/').TrimStart('/')
  if (-not $relative) { continue }
  if ($upload | Where-Object { (Get-RelativePath $_) -eq $relative }) {
    Write-Host "  [skip] $relative is both uploaded and removed - keeping the uploaded copy"
    continue
  }
  # a null sha deletes the path from the new tree
  $entries.Add(@{ path = $relative; mode = '100644'; type = 'blob'; sha = $null })
  Write-Host "  removed  $relative"
}

$treeBody = @{ tree = $entries.ToArray() }
if ($baseTree) { $treeBody.base_tree = $baseTree }
$tree = Invoke-GitHubApi -Method POST -Path "/repos/$Owner/$Repo/git/trees" -Body $treeBody

$commitBody = @{ message = $Message; tree = $tree.sha }
if ($headCommit) { $commitBody.parents = @($headCommit) }
$commit = Invoke-GitHubApi -Method POST -Path "/repos/$Owner/$Repo/git/commits" -Body $commitBody

if ($headCommit) {
  Invoke-GitHubApi -Method PATCH -Path "/repos/$Owner/$Repo/git/refs/heads/$Branch" -Body @{
    sha = $commit.sha
    force = $false
  } | Out-Null
} else {
  Invoke-GitHubApi -Method POST -Path "/repos/$Owner/$Repo/git/refs" -Body @{
    ref = "refs/heads/$Branch"
    sha = $commit.sha
  } | Out-Null
}

Write-Host ''
Write-Host "commit: https://github.com/$Owner/$Repo/commit/$($commit.sha)"
Write-Host "code:   https://github.com/$Owner/$Repo/tree/$Branch"

if ($ReleaseTag) {
  if (-not $ReleaseBody) {
    # Keep this script ASCII-only: Windows PowerShell reads .ps1 files as ANSI when
    # they have no BOM, which corrupts non-ASCII literals.  The release text lives in
    # docs/RELEASE-NOTES.md (Chinese) and docs/RELEASE-NOTES.en.md (English) instead;
    # both are published, separated by a rule.
    $chinese = Join-Path $root 'docs\RELEASE-NOTES.md'
    $english = Join-Path $root 'docs\RELEASE-NOTES.en.md'
    $parts = @()
    if (Test-Path $chinese) { $parts += (Get-Content $chinese -Raw -Encoding UTF8) }
    if (Test-Path $english) { $parts += (Get-Content $english -Raw -Encoding UTF8) }
    if ($parts.Count -gt 0) {
      $ReleaseBody = $parts -join "`n`n---`n`n"
    } else {
      $ReleaseBody = 'See README.md for install instructions, requirements and checksums.'
    }
  }
  # A release for this tag may already exist (a re-release that only replaces/extends the
  # attachments).  POSTing again would fail with 422, so an existing release is updated
  # in place: same tag, same URL, fresh body and attachments.
  $existing = $null
  try {
    $existing = Invoke-GitHubApi -Method GET -Path "/repos/$Owner/$Repo/releases/tags/$ReleaseTag"
  } catch {
    $existing = $null
  }
  if ($existing) {
    Write-Host "release $ReleaseTag already exists (id $($existing.id)) - updating it"
    $release = Invoke-GitHubApi -Method PATCH -Path "/repos/$Owner/$Repo/releases/$($existing.id)" -Body @{
      name = $ReleaseName
      body = $ReleaseBody
      draft = $false
      prerelease = $false
    }
  } else {
    $release = Invoke-GitHubApi -Method POST -Path "/repos/$Owner/$Repo/releases" -Body @{
      tag_name = $ReleaseTag
      name = $ReleaseName
      body = $ReleaseBody
      draft = $false
      prerelease = $false
    }
  }
  Write-Host "release: $($release.html_url)"

  # only the playable jars are published: the source already lives in the repository, so a
  # -sources.jar attachment would be redundant.  -Version keeps older builds that still sit
  # in dist/ from being attached to this release, and both the Forge and the NeoForge jar
  # match it, so one version publishes both loaders.
  $pattern = if ($Version) { "*$Version*.jar" } else { '*.jar' }
  $assets = @(Get-ChildItem (Join-Path $root 'dist') -Filter $pattern -ErrorAction SilentlyContinue |
      Where-Object { $_.Name -notlike '*-sources.jar' })
  if ($assets.Count -eq 0) { Write-Host "[warn] no release asset matched $pattern in dist/" }

  $existingAssets = @()
  try {
    $existingAssets = @(Invoke-GitHubApi -Method GET -Path "/repos/$Owner/$Repo/releases/$($release.id)/assets")
  } catch {
    Write-Host "[warn] could not list the release assets: $($_.Exception.Message)"
  }

  foreach ($asset in $assets) {
    $previous = $existingAssets | Where-Object { $_.name -eq $asset.Name } | Select-Object -First 1
    if ($previous -and $previous.size -eq $asset.Length) {
      Write-Host ("  asset: {0} already present with the same size ({1:N0} B) - left alone" -f $asset.Name, $asset.Length)
      continue
    }
    if ($previous) {
      Write-Host ("  asset: {0} differs ({1:N0} B on GitHub vs {2:N0} B locally) - replacing" -f `
          $asset.Name, $previous.size, $asset.Length)
      Invoke-GitHubApi -Method DELETE -Path "/repos/$Owner/$Repo/releases/assets/$($previous.id)" | Out-Null
    }
    $arguments = @(
      '-sS', '--ssl-no-revoke', '-X', 'POST', '-m', '1800',
      '-H', "Authorization: Bearer $Token",
      '-H', 'Accept: application/vnd.github+json',
      '-H', 'Content-Type: application/octet-stream',
      '-H', 'User-Agent: watermedia-android-bridge-uploader',
      '--data-binary', "@$($asset.FullName)",
      # the asset name goes into the query string: '+' must be percent-encoded or
      # GitHub stores the file as "...-1.0.4.mc1.21.1-neoforge.jar"
      "https://uploads.github.com/repos/$Owner/$Repo/releases/$($release.id)/assets?name=$([uri]::EscapeDataString($asset.Name))"
    )
    $result = (& curl.exe @arguments) -join ''
    $uploaded = $result | ConvertFrom-Json -ErrorAction SilentlyContinue
    if ($uploaded -and $uploaded.name -eq $asset.Name) {
      Write-Host ("  asset: {0} ({1:N1} MiB)" -f $uploaded.name, ($uploaded.size / 1MB))
    } elseif ($uploaded -and $uploaded.name) {
      Write-Host "  [warn] asset stored as '$($uploaded.name)', expected '$($asset.Name)'"
    } else {
      Write-Host "  [warn] asset upload failed for $($asset.Name): $result"
    }
  }
}

if ($Topics.Count -gt 0) {
  # Topics need the "Administration: write" repository permission; with a
  # Contents-only token this call is the one that fails, and everything else is
  # already pushed, so a failure here is reported but not fatal.
  # This has to run BEFORE the temp directory is removed - Invoke-GitHubApi writes
  # its request body there.
  try {
    $topicsResult = Invoke-GitHubApi -Method PUT -Path "/repos/$Owner/$Repo/topics" -Body @{ names = @($Topics) }
    Write-Host ("topics: " + ($topicsResult.names -join ', '))
  } catch {
    Write-Host "[warn] could not set topics (needs Administration: write): $($_.Exception.Message)"
  }
}

Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue
Write-Host 'done'
